version: "3"
services:
    jenkins:
        image: pyjenkins
        container_name: "jenkins_devwdougherty"
        ports:
            - "8000:8080"
            - "50000:50000"
        volumes:
            - "./jenkins_home_volume:/var/jenkins_home"
            - "./exchange:/exchange"
