name: Deploy Data Platform to Production

on:
  push:
    branches-ignore:
      - main

jobs:
  build-oop-exercise-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: oop-data-ingestion-tests-aws-github-actions

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-Python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: make ci-setup

      - name: Run Tests
        run: make ci-test
        
  build-oop-exercise-deploy:
    runs-on: ubuntu-latest
    needs: build-oop-exercise-test
    defaults:
      run:
        working-directory: oop-data-ingestion-tests-aws-github-actions

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-Python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: make ci-setup

      - name: Deploy
        env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: make ci-deploy stage=prod